### ISSUE TITLE
Dude, how do i set this up?!

### ISSUE THREAD

**Issue by francisleigh** [panekj/lapce-typescript#13]
Hey! 
Installed Lapce and immediately installed `lapce-typescript`

```bash
$ typescript-language-server --version
2.0.0
```

`typescript-language-server` is installed globally and available as a global in the terminal.

### Lapce settings.toml
```toml
[lapce-typescript.volt]
serverPath = ""
serverArgs = ["--stdio"]

[core]
icon-theme = "Material Icons"

[ui]
font-family = "Fire Code"
```

I have restarted Lapce and just for the life of me can't get Intellisense working at all. 

Any help would be appreciated!

**Comment by mateusduraes** [comment]
Hey man, maybe you found out how to use it already.
I installed lapce a few minutes ago and I was trying to use this plugin.

This is how I got it configured


In lapce `command` + `shift` + `p` and `Open settings file`

```toml
[core]
modal = false

[lapce-typescript]
"volt.serverPath" = "/Users/mateus/.npm-global/bin/typescript-language-server"
"volt.serverArgs" = "--stdio"

```

Also make sure to install the version 2 of the typescript language server. Not sure whether the plugin works with other versions.

```bash
npm i --global typescript-language-server@2 typescript
```

Maybe reloading Lapce or the plugin itself after that is a good idea.
